services:
  database:
    container_name: wheelgotrip-database
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdatabase
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-U', 'pguser', '-d', 'pgdatabase']
      start_period: 15s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - .pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    profiles:
      - dev

  minio:
    platform: linux/amd64
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_REGION: us-east-1
      MINIO_REGION_NAME: us-east-1
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    command: server /data/minio --console-address :9001
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - .minio-data/:/data
    profiles:
      - minio

  app-dev:
    container_name: wheelgotrip-server-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: wheelgotrip-server-dev
    pull_policy: build
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      database:
        condition: service_healthy
        restart: true
    profiles:
      - dev

  app-prod:
    container_name: wheelgotrip-server-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: wheelgotrip-server-prod
    pull_policy: build
    ports:
      - 3000:3000
    profiles:
      - prod
